#!/bin/bash
set -e

# Make link
ln -s /opt/tmpusb/bin/tmpusb /usr/bin/tmpusb 2>/dev/null || true

# Update MAN pages
mandb -q || true

# Just loading to suppress warning
. /usr/share/debconf/confmodule || true

# Done
exit 0
